### ISSUE TITLE
pipeline for automatic fMRIPrep output validation.

### ISSUE THREAD

**Issue by Vincent-wq** [neurodatascience/mr_proc#14]
We need a script to check the processing pipelines results so that we can make a quick diagnosis and debug:

1. Heudiconv:
I was counting the number of output subject folders and sge error logs., any recommendations?
2. fMRIPrep, we can check:
    2.1. the number of freesurfer stats files
    2.2  the number of files in subject folders in fmriprep and the number of the corresponding html report
3. TractoFlow:
    to be done.
4. SPM

**Comment by nikhil153** [comment]
@Vincent-wq 
Is this ready to be closed?

**Comment by michellewang** [comment]
Closing because this is (will be) handled by trackers
