### ISSUE TITLE
PPMI subject with BIDS but no demographics

### ISSUE THREAD

**Issue by surchs** [neurodatascience/mr_proc#33]
I noticed that the PPMI subject `sub-114526` is in the BIDS directory (and in the `/data/pd/ppmi/bids/participants.tsv` file), but is not in the `/data/pd/ppmi/tabular/demographics/participants.csv` file.

I'll exclude the subject from our annotation, but from what we discussed I think this should not happen. Maybe the subject was excluded or there is a typo in the name?

**Comment by nikhil153** [comment]
Maybe @Vincent-wq knows more about this. If not I will take a look at the list later.

**Comment by surchs** [comment]
just following up @Vincent-wq: do you have an idea why `sub-114526` ended up in the BIDS directory but we don't have a corresponding demographic record?
