### ISSUE TITLE
Error when running `pip install`

### ISSUE THREAD

**Issue by michellewang** [neurodatascience/mr_proc#53]
I am getting an error when running `pip install -e .` in the root directory:
```
Obtaining file:///data/origami/michelle/mr_proc
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      error: Multiple top-level packages discovered in a flat-layout: ['imgs', 'legacy', 'workflow', 'notebooks'].
      
      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.
      
      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:
      
      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names
      
      To find more information, look for "package discovery" on setuptools docs.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I can get around this by adding something like this in `setup.cfg`:
```
[options]
#...
packages = 
    workflow
```

Then `pip` installs the dependencies correctly.

**Comment by nikhil153** [comment]
Hmm this is odd - are you installing in a fresh env or an existing one? I just tried this on BIC in a fresh env and didn't get this error.

**Comment by michellewang** [comment]
Yes it was a fresh conda environment. Here's the output of `conda env export` (after `pip` installing the dependencies):
```
name: mr_proc
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgomp=12.2.0=h65d4601_19
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.40.0=h753d276_0
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.13=h166bdaf_4
  - ncurses=6.3=h27087fc_1
  - openssl=3.0.8=h0b41bf4_0
  - pip=23.0=pyhd8ed1ab_0
  - python=3.9.16=h2782a2a_0_cpython
  - readline=8.1.2=h0f457ee_0
  - setuptools=67.1.0=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tzdata=2022g=h191b570_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
    - joblib==1.2.0
    - nibabel==5.0.0
    - packaging==23.0
    - pandas==1.5.3
    - pydicom==2.3.1
    - six==1.16.0
prefix: /data/origami/michelle/miniconda3/envs/mr_proc
```

**Comment by michellewang** [comment]
Update: this might be a Python/`setuptools` version issue. I tried with fresh conda environments with Python 3.9, 3.8, 3.7, and 3.6 installed, and it only worked for Python 3.6 (with `setuptools` 58.0.4). It started failing with Python 3.7 and `setuptools` 67.1.0.

**Comment by nikhil153** [comment]
I see. Good to know as I had only tried with venvs and not conda.

**Comment by jbpoline** [comment]
Isn't 3.6 considered too old ? I suppose we don't care at that stage ?

**Comment by nikhil153** [comment]
the newer python versions work within venv. I am not sure what happens with conda.

**Comment by michellewang** [comment]
@nikhil153 I don't think it's a venv vs conda issue. It looks like newer versions of `setuptools` (>= 61.0.0) can throw this error (see [here](https://stackoverflow.com/questions/72294299/multiple-top-level-packages-discovered-in-a-flat-layout#comment131420464_72547402), and this [`setuptools` PR](https://github.com/pypa/setuptools/pull/2894)). Which version of `setuptools` did you use in your tests with venv?

**Comment by michellewang** [comment]
I just tested with Python 3.9.16 and conda, it works with `setuptools` 60.10.0 but I get error with the next version (61.0.0).

**Comment by nikhil153** [comment]
@michellewang I am using much older `setuptools=47.1.0`
I see, so `setuptools>=61.0.0` will throw an error regardless. Will specify that in the setup config.

**Comment by nikhil153** [comment]
Added [pyproject.toml](https://github.com/neurodatascience/mr_proc/blob/main/pyproject.toml) in the main branch to enforce setuptools version. 
@michellewang let me know if this works for you as well.

**Comment by michellewang** [comment]
Can confirm that it worked with a fresh Python 3.9 conda environment (`main` branch only) @nikhil153!
