### ISSUE TITLE
Figure out what to do about diverging branches

### ISSUE THREAD

**Issue by michellewang** [neurodatascience/mr_proc#61]
Each dataset has its own branch, but currently they are about 100 commits behind `main` and 100 commits ahead. We have tried discussing what to do to consolidate this but haven't come up with a good solution. 

Current proposed options:
1. Restart the branches for each dataset (start from current `main`, add additional code) and keep using branches for different datasets.
    * **Cons**: We might get similar problems in the future.
2. Have a single `main` branch in the base `mr_proc` repro, make forks (under `neurodatascience`) for each dataset, make individual forks and use PRs to add change. Pull/rebase on main `mr_proc` to get changes.

If anyone has thoughts on this, it would be great to discuss!

**Comment by michellewang** [comment]
Arrived at a better solution with @nikhil153 and @bcmcpher:
* Under the `neurodatascience` GitHub organization:
  * The main ("template") repository contains all common files `neurodatascience/mr_proc`
  * Make a fork for each dataset: `neurodatascience/mr_proc-[dataset]`
  * *Note: all repos have a projected `main` branch. Contributions should be done through PRs only.*
* Contribution rules:
  * Changes that apply to all datasets:
    * Make a user fork of `neurodatascience/mr_proc`: `[username]/mr_proc`
    * Clone `[username]/mr_proc` locally
    * Push to `[username]/mr_proc` on GitHub
    * PR from `[username]/mr_proc` to `neurodatascience/mr_proc`
  * Changes that apply to individual datasets
    * Clone `neurodatascience/mr_proc-[dataset]` locally
    * Make a new branch when working on a new feature
      * ***IMPORTANT***: need to be careful with branch names, they should be unique
    * PR from `neurodatascience/mr_proc-[dataset]:[feature_branch]` to `neurodatascience/mr_proc-[dataset]:main`
    * Delete branch when done

**Comment by nikhil153** [comment]
Completed with the #71
