### ISSUE TITLE
`bagel.(c)tsv` files would need an update for Neurobagel

### ISSUE THREAD

**Issue by surchs** [neurodatascience/mr_proc#99]
Hello folks, as mentioned in #33, `bagel.csv` files seem to be superseded by `mr_proc_manifest.csv` for the purpose of participant ID tracking. However Neurobagel still relies on a file in the format of the `bagel.csv` files, i.e. with 

- `bids_id`: BIDS subject ID
- age
- sex
- diagnostic status
- one-column-per cognitive test battery / assessment tool

Assuming that neurobagel is the only thing consuming these, could we also make them `.tsv` because that's the typical tabular format in BIDS land? That would help us a lot with conversions.

I collect our wishlist here:
- [x] Generate `bagel.csv` as Tab-Separated-Value format `bagel.tsv` 
- [x] https://github.com/neurodatascience/mr_proc-ppmi/issues/12
- [x] https://github.com/neurodatascience/mr_proc-qpn/issues/8

**Comment by alyssadai** [comment]
Closing as PPMI/QPN tabular bagels have been updated to include all subjects with BIDS data on disk and regenerated as .tsv files.
